/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje2;

import java.util.ArrayList;
import java.util.Scanner;
import java.util.StringTokenizer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class Tablo extends javax.swing.JFrame {

   String isim;
   ArrayList <String> numara = new ArrayList<String>();
   private static ciftBListe liste = new ciftBListe();                
   private static dosyaIslemleri dosya = new dosyaIslemleri();
   DefaultTableModel dtm = new DefaultTableModel();                // degiskenler
   DefaultTableModel dtm2 = new DefaultTableModel();
   
    public Tablo() {
        initComponents();
        jTable1.setModel(dtm);
        dtm.setColumnIdentifiers(new String [] {"Name","Number"});
        
        jTza.setModel(dtm2);
        dtm2.setColumnIdentifiers(new String [] {"Name","Number"});
    }
    
    public void tabloyaEkle()      // 1.tabloya verileri girer.
    {
        Node bilgi;
        int i,size;
        String ad,numara;
        
        bilgi = liste.dondur(0);
        while(dtm.getRowCount()>0)
        {
            for(i=0;i<dtm.getRowCount();i++)
            {
                dtm.removeRow(i);
            }
        }
        i=0;
        while(bilgi.getSonraki()!=null)
        {
        
        bilgi = liste.dondur(i);
        ad =bilgi.getBas().getAdSoyad();
        numara=bilgi.getBas().getTumNo() ;   
        dtm.addRow(new String []{ad,numara});
        i++;
        }
    }
    public void tabloyaEkle2()     // 2. tabloya verileri girer.
    {
        Node bilgi;
        int i,size;
        String ad,numara;
        
        bilgi = liste.dondur(0);
        while(dtm2.getRowCount()>0)
        {
            for(i=0;i<dtm2.getRowCount();i++)
            {
                dtm2.removeRow(i);
            }
        }
        
        bilgi = liste.getTail();
        while(bilgi!=null)
        {        
        ad =bilgi.getBas().getAdSoyad();
        numara=bilgi.getBas().getTumNo() ;   
        dtm2.addRow(new String []{ad,numara});
        bilgi=bilgi.getOnceki();       
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFad = new javax.swing.JTextField();
        jTFnumara = new javax.swing.JTextField();
        jBTekle = new javax.swing.JButton();
        jBTsil = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTFad2 = new javax.swing.JTextField();
        jBTbul = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBTrehber = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTza = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTFsonuc = new javax.swing.JTextField();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel1.setText("Name,Surname");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Number");

        jBTekle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBTekle.setForeground(new java.awt.Color(0, 204, 204));
        jBTekle.setText("Add");
        jBTekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTekleActionPerformed(evt);
            }
        });

        jBTsil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBTsil.setForeground(new java.awt.Color(255, 0, 0));
        jBTsil.setText("Delete");
        jBTsil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTsilActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Name------->");

        jBTbul.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBTbul.setForeground(new java.awt.Color(0, 0, 204));
        jBTbul.setText("Find");
        jBTbul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTbulActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBTrehber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBTrehber.setForeground(new java.awt.Color(0, 0, 204));
        jBTrehber.setText("Directory(open)");
        jBTrehber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTrehberActionPerformed(evt);
            }
        });

        jTza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTza);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 204));
        jLabel4.setText("Answer");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel5.setText(" Z---------> A       in ORder");

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setText("A-------->Z      in Order");

        jScrollPane4.setViewportView(jTFsonuc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBTekle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFnumara, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jTFad)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBTsil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBTbul, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFad2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBTrehber)
                                .addGap(183, 183, 183))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFnumara, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(jBTekle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFad2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBTsil, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBTbul, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBTrehber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBTekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTekleActionPerformed
       
        try{
           isim = jTFad.getText();
           numara.add(jTFnumara.getText());
           liste.alfabetikEkle(isim, numara);
           numara.clear();
           jTFsonuc.setText(isim+" -->Added");
           liste.yazdir();
           tabloyaEkle();
           tabloyaEkle2();
           dosya.dosyayiGuncelle(liste);
         }catch(Exception ex)
         {
             jTFsonuc.setText("Error!");
             numara.clear();
         }
    }//GEN-LAST:event_jBTekleActionPerformed

    private void jBTsilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTsilActionPerformed
        isim = jTFad2.getText();
        Node gecici = liste.seciliSil(isim);
        if(gecici==null)
        {
            jTFsonuc.setText("This person is not here!");
        }
        else
        {    liste.yazdir();
             jTFsonuc.setText(gecici.getBas().getAdSoyad()+" -->deleted");
             tabloyaEkle();
             tabloyaEkle2();
             dosya.dosyayiGuncelle(liste);
        }
    }//GEN-LAST:event_jBTsilActionPerformed

    private void jBTbulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTbulActionPerformed
       isim = jTFad2.getText();
       Node gecici = liste.seciliBul(isim);
       String numaralar="";
       if(gecici==null)
           jTFsonuc.setText("This person is not here!");
       else{
            int size = gecici.getBas().getNumaralar().size();
            int i=0;
            while(i<size)
            {
                 numaralar += gecici.getBas().getNumaralar().get(i)+"\n";
                 i++;
            }
             jTFsonuc.setText(gecici.getBas().getAdSoyad()+" numbers : "+numaralar);
       }
    }//GEN-LAST:event_jBTbulActionPerformed

    private void jBTrehberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTrehberActionPerformed
        try
        {
        tabloyaEkle();
        tabloyaEkle2();
        }catch(Exception ex)
        {
            jTFsonuc.setText("Directory is empty!");
        }
    }//GEN-LAST:event_jBTrehberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        ArrayList <String> numaralar = new ArrayList<String>();
        String isim;
        Scanner okuma = null;
        Scanner keybord = new Scanner(System.in) ;
       try {
        okuma = dosya.oku();
        int satirSay = dosya.satirSayisi();
        int i=0;
            
        numaralar.add("bos");
        liste.basaekle("aaaaaaaaaaaaaa", numaralar);      // Listeye alfabetik bir sekilde eleman ekleyebilmek icin
        liste.sonaekle("zzzzzzzzzzzzz", numaralar);      //Sonradan kaldirilmak uzere gecici bir alfabetik head ve tail ataniyor.
        numaralar.clear();
      
        
        for(i=0;i<satirSay;i++)
        {
            String a = dosya.satirOku(okuma);
            StringTokenizer str = new StringTokenizer(a,",");
            
            isim = str.nextToken();
            while(str.hasMoreTokens())
            {
                numaralar.add(str.nextToken()); 
            }
        
            liste.alfabetikEkle(isim, numaralar);
            numaralar.clear();
        }
        liste.seciliSil("aaaaaaaaaaaaaa");
        liste.seciliSil("zzzzzzzzzzzzz");               // head ve tail i tutan elemanlar gerek kalmadigindan kaldiriliyor...
        numaralar.clear();
        dosya.dosyayiGuncelle(liste);
       }catch(IndexOutOfBoundsException ex)
       {    
           liste.seciliSil("aaaaaaaaaaaaaa");
           liste.seciliSil("zzzzzzzzzzzzz");
           System.out.println("dosya bos mu ?");
       }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTbul;
    private javax.swing.JButton jBTekle;
    private javax.swing.JButton jBTrehber;
    private javax.swing.JButton jBTsil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTFad;
    private javax.swing.JTextField jTFad2;
    private javax.swing.JTextField jTFnumara;
    private javax.swing.JTextField jTFsonuc;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTza;
    // End of variables declaration//GEN-END:variables
}
